package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallFlashSalesRules;
import org.linlinjava.litemall.db.domain.LitemallFlashSalesRulesExample;

public interface LitemallFlashSalesRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    long countByExample(LitemallFlashSalesRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallFlashSalesRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    int insert(LitemallFlashSalesRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    int insertSelective(LitemallFlashSalesRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFlashSalesRules selectOneByExample(LitemallFlashSalesRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFlashSalesRules selectOneByExampleSelective(@Param("example") LitemallFlashSalesRulesExample example, @Param("selective") LitemallFlashSalesRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallFlashSalesRules> selectByExampleSelective(@Param("example") LitemallFlashSalesRulesExample example, @Param("selective") LitemallFlashSalesRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    List<LitemallFlashSalesRules> selectByExample(LitemallFlashSalesRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFlashSalesRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallFlashSalesRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    LitemallFlashSalesRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFlashSalesRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallFlashSalesRules record, @Param("example") LitemallFlashSalesRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallFlashSalesRules record, @Param("example") LitemallFlashSalesRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallFlashSalesRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallFlashSalesRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallFlashSalesRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}