package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallRecharge;
import org.linlinjava.litemall.db.domain.LitemallRechargeExample;

public interface LitemallRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    long countByExample(LitemallRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    int insert(LitemallRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    int insertSelective(LitemallRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRecharge selectOneByExample(LitemallRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRecharge selectOneByExampleSelective(@Param("example") LitemallRechargeExample example, @Param("selective") LitemallRecharge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallRecharge> selectByExampleSelective(@Param("example") LitemallRechargeExample example, @Param("selective") LitemallRecharge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    List<LitemallRecharge> selectByExample(LitemallRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRecharge selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallRecharge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    LitemallRecharge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRecharge selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallRecharge record, @Param("example") LitemallRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallRecharge record, @Param("example") LitemallRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_recharge
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}