package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallFlashSales;
import org.linlinjava.litemall.db.domain.LitemallFlashSalesExample;

public interface LitemallFlashSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    long countByExample(LitemallFlashSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallFlashSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    int insert(LitemallFlashSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    int insertSelective(LitemallFlashSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFlashSales selectOneByExample(LitemallFlashSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFlashSales selectOneByExampleSelective(@Param("example") LitemallFlashSalesExample example, @Param("selective") LitemallFlashSales.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallFlashSales> selectByExampleSelective(@Param("example") LitemallFlashSalesExample example, @Param("selective") LitemallFlashSales.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    List<LitemallFlashSales> selectByExample(LitemallFlashSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFlashSales selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallFlashSales.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    LitemallFlashSales selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFlashSales selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallFlashSales record, @Param("example") LitemallFlashSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallFlashSales record, @Param("example") LitemallFlashSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallFlashSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallFlashSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallFlashSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flash_sales
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}