package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ThirdPayHistory;
import org.linlinjava.litemall.db.domain.ThirdPayHistoryExample;

public interface ThirdPayHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    long countByExample(ThirdPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int deleteByExample(ThirdPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int insert(ThirdPayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int insertSelective(ThirdPayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    ThirdPayHistory selectOneByExample(ThirdPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    ThirdPayHistory selectOneByExampleSelective(@Param("example") ThirdPayHistoryExample example, @Param("selective") ThirdPayHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    List<ThirdPayHistory> selectByExampleSelective(@Param("example") ThirdPayHistoryExample example, @Param("selective") ThirdPayHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    List<ThirdPayHistory> selectByExample(ThirdPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    ThirdPayHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ThirdPayHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    ThirdPayHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    ThirdPayHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ThirdPayHistory record, @Param("example") ThirdPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ThirdPayHistory record, @Param("example") ThirdPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ThirdPayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThirdPayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ThirdPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_pay_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}