package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.UserBalanceHistory;
import org.linlinjava.litemall.db.domain.UserBalanceHistoryExample;

public interface UserBalanceHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    long countByExample(UserBalanceHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int deleteByExample(UserBalanceHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int insert(UserBalanceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int insertSelective(UserBalanceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    UserBalanceHistory selectOneByExample(UserBalanceHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    UserBalanceHistory selectOneByExampleSelective(@Param("example") UserBalanceHistoryExample example, @Param("selective") UserBalanceHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    List<UserBalanceHistory> selectByExampleSelective(@Param("example") UserBalanceHistoryExample example, @Param("selective") UserBalanceHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    List<UserBalanceHistory> selectByExample(UserBalanceHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    UserBalanceHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") UserBalanceHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    UserBalanceHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    UserBalanceHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserBalanceHistory record, @Param("example") UserBalanceHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserBalanceHistory record, @Param("example") UserBalanceHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBalanceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBalanceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") UserBalanceHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_balance_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}